### ISSUE TITLE
Not showing the data correctly

### ISSUE THREAD

**Issue by awangca** [20chix/course_Vue.js_Mongo_Express.js#3]
[{"_id":"5a2f25a3638e2616eefeb2bc","__v":0,"Created_date":"2017-12-12T00:41:07.958Z"},{"_id":"5a2f28e0fa4de91a4f3e4a22","__v":0,"Created_date":"2017-12-12T00:54:56.406Z"},{"_id":"5a2f28e9fa4de91a4f3e4a23","__v":0,"Created_date":"2017-12-12T00:55:05.102Z"},{"_id":"5a2f2e8ed487fa099e7a2342","__v":0,"Created_date":"2017-12-12T01:19:10.967Z"},{"_id":"5a2f2e8fd487fa099e7a2343","__v":0,"Created_date":"2017-12-12T01:19:11.517Z"},{"_id":"5a2f2f21dc9d9b0a5c800d66","__v":0,"Created_date":"2017-12-12T07:59:58.133Z"},{"_id":"5a2f2fdf934a9e0ae80f03f6","__v":0,"Created_date":"2017-12-12T01:24:47.811Z"},{"_id":"5a2f2fef934a9e0ae80f03f7","__v":0,"Created_date":"2017-12-12T01:25:03.705Z"},{"_id":"5a2f58cf7c58bc09e2901869","__v":0,"Created_date":"2017-12-12T04:19:27.625Z"},{"_id":"5a2f58d27c58bc09e290186a","__v":0,"Created_date":"2017-12-12T04:19:30.445Z"},{"_id":"5a2f58df7c58bc09e290186b","__v":0,"Created_date":"2017-12-12T04:19:43.000Z"},{"_id":"5a2f59862b024d0ac04b8614","__v":0,"Created_date":"2017-12-12T04:22:30.348Z"},{"_id":"5a2f7ebe7b096510a4c9f029","__v":0,"Created_date":"2017-12-12T07:01:18.361Z"},{"_id":"5a2f7ebf7b096510a4c9f02a","__v":0,"Created_date":"2017-12-12T07:01:19.024Z"},{"_id":"5a2f7edc7b096510a4c9f02b","__v":0,"Created_date":"2017-12-12T07:01:48.013Z"},{"_id":"5a2f7ee97b096510a4c9f02c","__v":0,"Created_date":"2017-12-12T07:02:01.518Z"},{"_id":"5a2f7eea7b096510a4c9f02d","__v":0,"Created_date":"2017-12-12T07:02:02.096Z"}]

**Comment by 20chix** [comment]
What you mean not showing data correctly?
